<a href="https://colab.research.google.com/github/cyuancheng/Machine_Learning_Practice/blob/master/MissingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a CSV file with missing date

In [0]:
import pandas as pd
import numpy as np
from io import StringIO

In [0]:
CSV_data= \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,, 8.0
10.0,11.0,12.0,'''


In [0]:
df=pd.read_csv(StringIO(CSV_data))

In [16]:
df.head()

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

count missing value for each column

In [18]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

#### Drop missing value

In [23]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [21]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

### Impute missing value

##### 1) Imputer from sklearn 

In [31]:
from sklearn.preprocessing import Imputer
imputer_mean = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputed_mean_data = imputer_mean .fit_transform(df.values)

imputer_mostfreq = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imputed_mostfreq_data = imputer_mostfreq.fit_transform(df.values)

print('Impute mean value to missing data')
print(imputed_mean_data)
print('\nImpute most frequent value to missing data')
print(imputed_mostfreq_data)

Impute mean value to missing data
[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.5  8. ]
 [10.  11.  12.   6. ]]

Impute most frequent value to missing data
[[ 1.  2.  3.  4.]
 [ 5.  6.  3.  8.]
 [10. 11. 12.  4.]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
